:toc: left
:toc-title: Table des matières
:doctype: book

ifndef::imagesdir[] 
:imagesdir: assets
endif::[]

= {scmref} - Document 01 {scmref}

Contain under main title

[abstract]
--
*Version:* {scmref} {scmdate} #{scmcommit}

*publish-confluence:* {publish-confluence}

*backend-html5:* {backend-html5}

*backend-pdf:* {backend-pdf}
--

ifdef::backend-html5[]
/!\ This content is only for html5 and confluence (because publishToConfluence use backend-html5).
endif::[]

ifdef::publish-confluence[]
This content is only for confluence.
endif::[]

== Title A

Contain A

.Test resdScmInfo.gradle
[source,asciidoc,subs="attributes"]
----

revnumber = {revnumber}

revdate = {revdate}

javaVersion = {javaVersion}

scmref = {scmref}

scmdate = {scmdate}

scmcommit = {scmcommit}

scmurl = {scmurl}

----

.Test collapsable
[%collapsible]
====
Example block turns into collapsible summary/details with title. 

WARNING: Wolpertingers are known to nest in server racks.
Enter at your own risk.

====

[TIP]
.Feeding the Werewolves
====
While werewolves are hardy community members, keep in mind the following dietary concerns:

. They are allergic to cinnamon.
. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.
====

.Test raw html
++++
<ac:structured-macro 
    ac:schema-version="1"
    ac:name="scroll-version-navigation"      
    data-layout="default" />
++++

=== Title A1

Contain A1

=== Title A2

Contain A2

== Title B

Contain B

=== Title B1

Contain B1

=== Title B2

Contain B2

= Test several root title level bis (book mode)

Contain Test several root title level bis

== Test several root title level bis with subtitle

Contain Test several root title level bis with subtitle

:leveloffset: +1

// <<<
// include::chapiter-01.adoc[]

:leveloffset: -1




